feature change for security

diff --git a/bin/hostinfo b/bin/hostinfo
--- a/bin/hostinfo
+++ b/bin/hostinfo
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Description: Displays basic system information
-# Modified:    2014 Feb 12
+# Modified:    2014 Feb 25
 
 ##############################################################################
 #  Copyright (C) 2014 SUSE LLC
@@ -25,31 +25,23 @@
 ##############################################################################
 
 ##############################################################################
-# variables
+# Variables
 ##############################################################################
-SVER=0.8.3
+SVER=1.0.6
 PAD=25
-FORCE_UPDATE=0
-IGNORE_UPDATES=0
-IGNORE_NET=0
-IGNORE_MEM=0
-IGNORE_DISK=0
-
+QUIET=0
 FORMAT_OUT="%-${PAD}s %s\n"
-MISSING=$(mktemp /tmp/hostinfo.missing.XXXXXXXXXXXXXXX)
-OPT_DISPLAY_DISK_FREE=0
-INIT_FILE='/etc/hostinforc'
-if [[ -s $INIT_FILE ]]
+
+if [[ -s /etc/hostinforc ]]
 then
-	. $INIT_FILE
+	. /etc/hostinforc
 else
-	echo "ERROR: Missing hostinfo initialization file: $INIT_FILE"
-	echo
-	exit 1
+	echo "Error: Missing /etc/hostinforc"
+	exit 2
 fi
 
 ##############################################################################
-# functions
+# Functions
 ##############################################################################
 showHelp()
 {
@@ -62,14 +54,9 @@ showHelp()
 	echo " -m Ignore memory output"
 	echo " -d Ignore disk output"
 	echo " -u Ignore updates output"
-	echo " -f Force Pending updates"
+	echo " -q Quiet mode"
+	echo " -v View the current root-motd"
 	echo
-}
-
-forceUpdate()
-{
-	hrLine
-	hostinfo-updates -v
 }
 
 exit_code() {
@@ -82,31 +69,65 @@ exit_code() {
 
 showHostname()
 {
-	printf "$FORMAT_OUT" "Hostname:" "$(hostname)"
+	if (( QUIET ))
+	then
+		printf "$FORMAT_OUT" "Hostname:" "$(hostname)" >> $FILE_ROOT_MOTD
+	else
+		printf "$FORMAT_OUT" "Hostname:" "$(hostname)" | tee -a $FILE_ROOT_MOTD
+	fi
+}
+
+hrLine()
+{
+	if (( QUIET ))
+	then
+		echo '-----------------------------------------------------------' >> $FILE_ROOT_MOTD
+	else
+		echo '-----------------------------------------------------------' | tee -a $FILE_ROOT_MOTD
+	fi
+}
+
+emptyLine()
+{
+	if (( QUIET ))
+	then
+		echo >> $FILE_ROOT_MOTD
+	else
+		echo | tee -a $FILE_ROOT_MOTD
+	fi
 }
 
 showDate()
 {
-	printf "$FORMAT_OUT" "Current Date:" "$(date '+%c')"
+	if (( QUIET ))
+	then
+		printf "$FORMAT_OUT" "Current As Of:" "$(date '+%c')" >> $FILE_ROOT_MOTD
+	else
+		printf "$FORMAT_OUT" "Current As Of:" "$(date '+%c')" | tee -a $FILE_ROOT_MOTD
+	fi
 }
 
 showDistribution()
 {
-	printf "$FORMAT_OUT" "Distribution:" "$(cat /etc/SuSE-release | grep SUSE | cut -d'(' -f1)"
-	printf "$FORMAT_OUT" " -Service Pack:" "$(cat /etc/SuSE-release | grep PATCHLEVEL | awk '{print $3}')"
+	if (( QUIET ))
+	then
+		printf "$FORMAT_OUT" "Distribution:" "$(cat /etc/SuSE-release | grep SUSE | cut -d'(' -f1)" >> $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Service Pack:" "$(cat /etc/SuSE-release | grep PATCHLEVEL | awk '{print $3}')" >> $FILE_ROOT_MOTD
+	else
+		printf "$FORMAT_OUT" "Distribution:" "$(cat /etc/SuSE-release | grep SUSE | cut -d'(' -f1)" | tee -a $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Service Pack:" "$(cat /etc/SuSE-release | grep PATCHLEVEL | awk '{print $3}')" | tee -a $FILE_ROOT_MOTD
+	fi
 }
 
 showKernel()
 {
 	KERNEL_STR=$(uname -r)
-	printf "$FORMAT_OUT" "Architecture:" "$(uname -i)"
-	printf "$FORMAT_OUT" "Kernel Version:" "$KERNEL_STR"
 	KERN_RPM="kernel-$(echo $KERNEL_STR | awk -F- '{print $NF}')"
 	KERN_DATE=$(rpm -q --queryformat "%{INSTALLTIME:date}" $KERN_RPM 2>/dev/null)
 	if [[ -n "$KERN_DATE" ]]; then
-		printf "$FORMAT_OUT" " -Installed:" "$KERN_DATE"
+		KERN_DATE_STR="$KERN_DATE"
 	else
-		printf "$FORMAT_OUT" " -Installed:" "Unknown"
+		KERN_DATE_STR="Unknown"
 	fi
 	TAINT=$(cat /proc/sys/kernel/tainted)
 	TAINTED=0
@@ -132,16 +153,23 @@ showKernel()
 		test $((TAINT & 1024))       -ne 0 && TAINT_STRING="${TAINT_STRING}C" || TAINT_STRING="${TAINT_STRING} "
 		test $((TAINT & 1073741824)) -ne 0 && TAINT_STRING="${TAINT_STRING}N" || TAINT_STRING="${TAINT_STRING} "
 		test $((TAINT & 2147483648)) -ne 0 && TAINT_STRING="${TAINT_STRING}X" || TAINT_STRING="${TAINT_STRING} "
-		printf "$FORMAT_OUT" " -Status:" "Tainted: $TAINT_STRING"
+		KERN_TAINT_STR="Tainted: $TAINT_STRING"
 	else
-		printf "$FORMAT_OUT" " -Status:" "Not Tainted"
+		KERN_TAINT_STR="Not Tainted"
 	fi
 
-}
-
-hrLine()
-{
-	echo '-----------------------------------------------------------'
+	if (( QUIET ))
+	then
+		printf "$FORMAT_OUT" "Architecture:" "$(uname -i)" >> $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" "Kernel Version:" "$KERNEL_STR" >> $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Installed:" "$KERN_DATE_STR" >> $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Status:" "$KERN_TAINT_STR" >> $FILE_ROOT_MOTD
+	else
+		printf "$FORMAT_OUT" "Architecture:" "$(uname -i)" | tee -a $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" "Kernel Version:" "$KERNEL_STR" | tee -a $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Installed:" "$KERN_DATE_STR" | tee -a $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Status:" "$KERN_TAINT_STR" | tee -a $FILE_ROOT_MOTD
+	fi
 }
 
 showNetAddr()
@@ -170,14 +198,20 @@ showNetAddr()
          then
 				if [[ -n "$IADDR" ]]
 				then
-					printf "$FORMAT_OUT" "IPv4 Address:" "$IFACE $IADDR"
+					IPADDR_STR="$IFACE $IADDR"
 				else
-					printf "$FORMAT_OUT" "IPv4 Address:" "$IFACE (Unconfigured)"
+					IPADDR_STR="$IFACE (Unconfigured)"
 				fi
             IFACE=''
             IADDR=''
             STATE=1
             FIRST=1
+				if (( QUIET ))
+				then
+					printf "$FORMAT_OUT" "IPv4 Address:" "$IPADDR_STR" >> $FILE_ROOT_MOTD
+				else
+					printf "$FORMAT_OUT" "IPv4 Address:" "$IPADDR_STR" | tee -a $FILE_ROOT_MOTD
+				fi
          fi
       elif [[ -z "$LINE" ]]
       then
@@ -189,35 +223,72 @@ showNetAddr()
 
 showUpdates()
 {
-	if [[ -s $FILE_LAST_PACKAGE ]]
+	LIP_ALL=$(rpm -qa --last | head -1)
+	LIP_NAME=$(echo $LIP_ALL | cut -d' ' -f1)
+	LIP_DATE=$(echo $LIP_ALL | sed -e "s/${LIP_NAME}[[:space:]]*//g")
+	if (( QUIET ))
 	then
-		OUTPUT=$(cat $FILE_LAST_PACKAGE)
+		printf "$FORMAT_OUT" "Last Updated Package:" "$LIP_DATE" >> $FILE_ROOT_MOTD
 	else
-		OUTPUT="Pending"
+		printf "$FORMAT_OUT" "Last Updated Package:" "$LIP_DATE" | tee -a $FILE_ROOT_MOTD
 	fi
-	printf "$FORMAT_OUT" "Last Updated Package:" "$OUTPUT"
-	if [[ -s $FILE_PATCH_CHECK ]]
+
+	REPOS=$(zypper --non-interactive --no-gpg-checks repos | grep '^[[:digit:]]' | wc -l)
+	if (( REPOS > 1 ))
 	then
-		OUTPUT_N=$(cat $FILE_PATCH_CHECK | cut -d\| -f1)
-		OUTPUT_S=$(cat $FILE_PATCH_CHECK | cut -d\| -f2)
+		PATCH_STRING=$(zypper --non-interactive --no-gpg-checks patch-check | tail -1 | grep -i patches 2>/dev/null)
+		if [[ -n "$PATCH_STRING" ]]
+		then
+			PATCH_COUNT_NEEDED=$(echo $PATCH_STRING | cut -d' ' -f1)
+			PATCH_COUNT_SECURITY=$(echo $PATCH_STRING | cut -d\( -f2 | cut -d' ' -f1)
+		else
+			PATCH_COUNT_NEEDED='Pending'
+			PATCH_COUNT_SECURITY='Pending'
+		fi
 	else
-		OUTPUT_N="Pending"
-		OUTPUT_S="Pending"
+		PATCH_COUNT_NEEDED='Not Registered'
+		PATCH_COUNT_SECURITY='Not Registered'
 	fi
-	printf "$FORMAT_OUT" " -Patches Needed:" "$OUTPUT_N"
-	printf "$FORMAT_OUT" " -Security:" "$OUTPUT_S"
-	if [[ -s $FILE_NON_VENDOR_PACKAGES ]]
+	if (( QUIET ))
 	then
-		OUTPUT=$(cat $FILE_NON_VENDOR_PACKAGES)
+		printf "$FORMAT_OUT" " -Patches Needed:" "$PATCH_COUNT_NEEDED" >> $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Security:" "$PATCH_COUNT_SECURITY" >> $FILE_ROOT_MOTD
 	else
-		OUTPUT="Pending"
+		printf "$FORMAT_OUT" " -Patches Needed:" "$PATCH_COUNT_NEEDED" | tee -a $FILE_ROOT_MOTD
+		printf "$FORMAT_OUT" " -Security:" "$PATCH_COUNT_SECURITY" | tee -a $FILE_ROOT_MOTD
 	fi
-	printf "$FORMAT_OUT" " -3rd Party Packages:" "$OUTPUT"
+
+	COUNT_NVR=$(rpm -qa --queryformat "%{DISTRIBUTION}|%{NAME}\n" | egrep -iv "^SUSE:SLE-12:GA|^SUSE Linux Enterprise|gpg-pubkey$" | wc -l)
+	if (( QUIET ))
+	then
+		printf "$FORMAT_OUT" " -3rd Party Packages:" "$COUNT_NVR" >> $FILE_ROOT_MOTD
+	else
+		printf "$FORMAT_OUT" " -3rd Party Packages:" "$COUNT_NVR" | tee -a $FILE_ROOT_MOTD
+	fi
 }
 
 showMemory()
 {
-	printf "$FORMAT_OUT" "Total/Free Memory:" "$(cat /proc/meminfo | grep MemTotal: | awk '{printf "%i", $2/1024}')/$(cat /proc/meminfo | grep MemFree: | awk '{printf "%i", $2/1024}') MB"
+	MEM_TOTAL=$(cat /proc/meminfo | grep MemTotal: | awk '{printf "%i", $2/1024}')
+	MEM_FREE=$(cat /proc/meminfo | grep MemFree: | awk '{printf "%i", $2/1024}')
+	if [[ -x /usr/bin/free ]]
+	then
+		MEM_CACHE=$(/usr/bin/free -k | grep '^-' | awk '{printf "%i", $NF/1024}')
+		MEM_PERCENT=$(printf "%i" $(( MEM_CACHE * 100 / MEM_TOTAL )))
+		if (( QUIET ))
+		then
+			printf "$FORMAT_OUT" "Total/Free/+Cache Memory:" "${MEM_TOTAL}/${MEM_FREE}/${MEM_CACHE} MB (${MEM_PERCENT}% Free)" >> $FILE_ROOT_MOTD
+		else
+			printf "$FORMAT_OUT" "Total/Free/+Cache Memory:" "${MEM_TOTAL}/${MEM_FREE}/${MEM_CACHE} MB (${MEM_PERCENT}% Free)" | tee -a $FILE_ROOT_MOTD
+		fi
+	else
+		if (( QUIET ))
+		then
+			printf "$FORMAT_OUT" "Total/Free Memory:" "${MEM_TOTAL}/${MEM_FREE} MB" >> $FILE_ROOT_MOTD
+		else
+			printf "$FORMAT_OUT" "Total/Free Memory:" "${MEM_TOTAL}/${MEM_FREE} MB" | tee -a $FILE_ROOT_MOTD
+		fi
+	fi
 }
 
 showDisks()
@@ -228,28 +299,44 @@ showDisks()
 	fi
 	echo "$DISK_SIZES" | while read DISK_INFO
 	do
-		DEV_CHECK=$(echo $DISK_INFO | awk '{print $1}')
-		DISK_FREE=0
-		if (( OPT_DISPLAY_DISK_FREE )); then
-			for DISK_ADD in $(df | grep ^${DEV_CHECK} | awk '{print $4}')
-			do
-				DISK_FREE=$(( DISK_FREE + DISK_ADD ))
-			done
-		fi
-		if (( DISK_FREE )); then
-			DISK_INFO="$DISK_INFO $DISK_FREE"
-			THIS_DISK=$(echo $DISK_INFO | awk '{printf "%s %u/%u %s\n", $1, $2, $4*1024/1000^3, $3}')
+		THIS_DISK=$(echo $DISK_INFO | awk '{printf "%s %u %s\n", $1, $2, $3}')
+		if (( QUIET ))
+		then
+			printf "$FORMAT_OUT" "Hard Disk:" "$THIS_DISK" >> $FILE_ROOT_MOTD
 		else
-			THIS_DISK=$DISK_INFO
+			printf "$FORMAT_OUT" "Hard Disk:" "$THIS_DISK" | tee -a $FILE_ROOT_MOTD
 		fi
-		printf "$FORMAT_OUT" "Hard Disk:" "$THIS_DISK"
 	done
+}
+
+displayCurrentDate()
+{
+	if ! (( QUIET ))
+	then
+		echo
+		printf "$FORMAT_OUT" "Current Date:" "$(date '+%c')"
+	fi
+}
+
+showRootMotd()
+{
+	if [[ -s $FILE_ROOT_MOTD ]]
+	then
+		if grep "Hostname:" $FILE_ROOT_MOTD &> /dev/null
+		then
+			displayCurrentDate
+			DATE_NEEDED=0
+			cat $FILE_ROOT_MOTD
+			exit 0
+		fi
+	fi
 }
 
 ##############################################################################
 # main
 ##############################################################################
-while getopts :hfnmdu TMPOPT
+DATE_NEEDED=1
+while getopts :hnmdquv TMPOPT
 do
 	case $TMPOPT in
 	\:)	showHelp
@@ -269,11 +356,13 @@ do
 	d) IGNORE_DISK=1 ;;
 	u) IGNORE_UPDATES=1 ;;
 	h) showHelp; exit 0 ;;
-	f) FORCE_UPDATE=1 ;;
+	q) QUIET=1 ;;
+	v) showRootMotd ;;
 	esac
 done
 
-(( FORCE_UPDATE )) && forceUpdate
+(( DATE_NEEDED )) && displayCurrentDate
+> $FILE_ROOT_MOTD
 hrLine
 showHostname
 showDate
@@ -284,5 +373,5 @@ showKernel
 (( IGNORE_MEM )) || showMemory
 (( IGNORE_DISK )) || showDisks
 hrLine
-rm -rf $MISSING
-echo
+emptyLine
+
